export default {
  skills: [
    {
      source: "./assets/images/icons/Bash-Dark.svg",
      alternate: "Bash",
      title: "Bash",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/Bootstrap.svg",
      alternate: "Bootstrap",
      title: "Bootstrap",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/images/icons/Bun-Dark.svg",
      alternate: "Bun",
      title: "Bun",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/CodePen-Dark.svg",
      alternate: "CodePen",
      title: "CodePen",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/CPP.svg",
      alternate: "C++",
      title: "C++",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/CSS.svg",
      alternate: "CSS",
      title: "CSS",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/Debian-Dark.svg",
      alternate: "Debian",
      title: "Debian",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/images/icons/Discord.svg",
      alternate: "Discord",
      title: "Discord",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/images/icons/DiscordJS-Dark.svg",
      alternate: "Discord.js",
      title: "Discord.js",
      type: "ไลบลารี",
      description: "",
    },
    {
      source: "./assets/images/icons/Docker.svg",
      alternate: "Docker",
      title: "Docker",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Figma-Dark.svg",
      alternate: "Figma",
      title: "Figma",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Firebase-Dark.svg",
      alternate: "Firebase",
      title: "Firebase",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/images/icons/GCP-Dark.svg",
      alternate: "Google Cloud",
      title: "Google Cloud",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/images/icons/Git.svg",
      alternate: "Git",
      title: "Git",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/GithubActions-Dark.svg",
      alternate: "Github Actions",
      title: "Github Actions",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Github-Dark.svg",
      alternate: "Github",
      title: "Github",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/images/icons/Heroku.svg",
      alternate: "Heroku",
      title: "Heroku",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/images/icons/HTML.svg",
      alternate: "HTML",
      title: "HTML",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/Htmx-Dark.svg",
      alternate: "HTMX",
      title: "HTMX",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/Java-Dark.svg",
      alternate: "Java",
      title: "Java",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/JavaScript.svg",
      alternate: "JavaScript",
      title: "JavaScript",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/Jest.svg",
      alternate: "Jest",
      title: "Jest",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Kali-Dark.svg",
      alternate: "Kali",
      title: "Kali",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/images/icons/Kubernetes.svg",
      alternate: "Kubernetes",
      title: "Kubernetes",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/LinkedIn.svg",
      alternate: "LinkedIn",
      title: "LinkedIn",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/images/icons/Linux-Dark.svg",
      alternate: "Linux",
      title: "Linux",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/images/icons/Markdown-Dark.svg",
      alternate: "Markdown",
      title: "Markdown",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/MySQL-Dark.svg",
      alternate: "MySQL",
      title: "MySQL",
      type: "ฐานข้อมูล",
      description: "",
    },
    {
      source: "./assets/images/icons/NextJS-Dark.svg",
      alternate: "Next.js",
      title: "Next.js",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/images/icons/Nginx.svg",
      alternate: "Nginx",
      title: "Nginx",
      type: "เซิร์ฟเวอร์",
      description: "",
    },
    {
      source: "./assets/images/icons/NodeJS-Dark.svg",
      alternate: "Node.js",
      title: "Node.js",
      type: "รันไทม์",
      description: "",
    },
    {
      source: "./assets/images/icons/Notion-Dark.svg",
      alternate: "Notion",
      title: "Notion",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/images/icons/Npm-Dark.svg",
      alternate: "NPM",
      title: "NPM",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/NuxtJS-Dark.svg",
      alternate: "Nuxt.js",
      title: "Nuxt.js",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/images/icons/Photoshop.svg",
      alternate: "Photoshop",
      title: "Photoshop",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/images/icons/PostgreSQL-Dark.svg",
      alternate: "PostgreSQL",
      title: "PostgreSQL",
      type: "ฐานข้อมูล",
      description: "",
    },
    {
      source: "./assets/images/icons/Postman.svg",
      alternate: "Postman",
      title: "Postman",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Powershell-Dark.svg",
      alternate: "Powershell",
      title: "Powershell",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Python-Dark.svg",
      alternate: "Python",
      title: "Python",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/images/icons/React-Dark.svg",
      alternate: "React",
      title: "React",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/images/icons/Replit-Dark.svg",
      alternate: "Replit",
      title: "Replit",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Sketchup-Dark.svg",
      alternate: "Sketchup",
      title: "Sketchup",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/images/icons/SQLite.svg",
      alternate: "SQLite",
      title: "SQLite",
      type: "ฐานข้อมูล",
      description: "",
    },
    {
      source: "./assets/images/icons/StackOverflow-Dark.svg",
      alternate: "StackOverflow",
      title: "StackOverflow",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/images/icons/Supabase-Dark.svg",
      alternate: "Supabase",
      title: "Supabase",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/images/icons/TailwindCSS-Dark.svg",
      alternate: "TailwindCSS",
      title: "TailwindCSS",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/images/icons/Vercel-Dark.svg",
      alternate: "Vercel",
      title: "Vercel",
      type: "โฮสต์",
      description: "",
    },
    {
      source: "./assets/images/icons/VisualStudio-Dark.svg",
      alternate: "Visual Studio",
      title: "Visual Studio",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/Vite-Dark.svg",
      alternate: "Vite",
      title: "Vite",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/VSCode-Dark.svg",
      alternate: "Visual Studio Code",
      title: "Visual Studio Code",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/images/icons/VueJS-Dark.svg",
      alternate: "Vue.js",
      title: "Vue.js",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/images/icons/Windows-Dark.svg",
      alternate: "Windows",
      title: "Windows",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/images/icons/Yarn-Dark.svg",
      alternate: "Yarn",
      title: "Yarn",
      type: "เครื่องมือ",
      description: "",
    },
  ],
  portfolio: [
    {
      source: "./assets/images/portfolio/hamtarot.webp",
      alternate: "HAMTAROT",
      title: "HAMTAROT",
      description:
        "เว็บไซต์ทํานายดวงชะตาด้วยไพ่ทาโรต์ที่สร้างขึ้นด้วย Nuxt.js (Vue)",
      link: "https://github.com/66022523/HAMTAROT",
      tags: ["สื่อบันเทิง", "โหราศาสตร์"],
    },
    {
      source: "./assets/images/portfolio/mixit.webp",
      alternate: "MIXIT",
      title: "MIXIT",
      description: "ชุมชนเกมขนาดใหญ่จากทั่วทุกมุมโลกสร้างด้วย Next.js (React)",
      link: "https://github.com/66022523/MIXIT",
      tags: ["เกม", "ชุมชน", "สื่อสังคม"],
    },
    {
      source: "./assets/images/portfolio/up-e-services.webp",
      alternate: "UP E-Services",
      title: "UP E-Services",
      description: "ศูนย์รวมบริการทั้งหมดที่มีในมหาวิทยาลัยพะเยา",
      link: "https://www.figma.com/proto/QCxXTpypCNuXWh7YbLs2Es/Figma-Prototype-(%E0%B8%81%E0%B8%A5%E0%B8%B8%E0%B9%88%E0%B8%A1-7)?node-id=711-9933&node-type=instance&t=hjytkQ7JDdVRtd5i-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=711%3A5508",
      tags: ["ตัวอย่าง", "ออกแบบ", "แอปพลิเคชัน"],
    },
    {
      source: "./assets/images/portfolio/atbank.webp",
      alternate: "ATBank",
      title: "ATBank",
      description:
        "ตัวอย่างของแอปธนาคารที่สร้างขึ้นด้วย NetBeans บน Java (Maven)",
      link: "https://github.com/66022523/atbank",
      tags: ["ตัวอย่าง", "โปรแกรม"],
    },
  ],
};
