export default {
  skills: [
    {
      source: "./assets/icons/Bash-Dark.svg",
      alternate: "Bash",
      title: "Bash",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/Bootstrap.svg",
      alternate: "Bootstrap",
      title: "Bootstrap",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/icons/Bun-Dark.svg",
      alternate: "Bun",
      title: "Bun",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/CodePen-Dark.svg",
      alternate: "CodePen",
      title: "CodePen",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/CPP.svg",
      alternate: "C++",
      title: "C++",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/CSS.svg",
      alternate: "CSS",
      title: "CSS",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/Debian-Dark.svg",
      alternate: "Debian",
      title: "Debian",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/icons/Discord.svg",
      alternate: "Discord",
      title: "Discord",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/icons/DiscordJS-Dark.svg",
      alternate: "Discord.js",
      title: "Discord.js",
      type: "ไลบลารี",
      description: "",
    },
    {
      source: "./assets/icons/Docker.svg",
      alternate: "Docker",
      title: "Docker",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Figma-Dark.svg",
      alternate: "Figma",
      title: "Figma",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Firebase-Dark.svg",
      alternate: "Firebase",
      title: "Firebase",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/icons/GCP-Dark.svg",
      alternate: "Google Cloud",
      title: "Google Cloud",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/icons/Git.svg",
      alternate: "Git",
      title: "Git",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/GithubActions-Dark.svg",
      alternate: "Github Actions",
      title: "Github Actions",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Github-Dark.svg",
      alternate: "Github",
      title: "Github",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/icons/Heroku.svg",
      alternate: "Heroku",
      title: "Heroku",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/icons/HTML.svg",
      alternate: "HTML",
      title: "HTML",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/Htmx-Dark.svg",
      alternate: "HTMX",
      title: "HTMX",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/Java-Dark.svg",
      alternate: "Java",
      title: "Java",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/JavaScript.svg",
      alternate: "JavaScript",
      title: "JavaScript",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/Jest.svg",
      alternate: "Jest",
      title: "Jest",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Kali-Dark.svg",
      alternate: "Kali",
      title: "Kali",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/icons/Kubernetes.svg",
      alternate: "Kubernetes",
      title: "Kubernetes",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/LinkedIn.svg",
      alternate: "LinkedIn",
      title: "LinkedIn",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/icons/Linux-Dark.svg",
      alternate: "Linux",
      title: "Linux",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/icons/Markdown-Dark.svg",
      alternate: "Markdown",
      title: "Markdown",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/MySQL-Dark.svg",
      alternate: "MySQL",
      title: "MySQL",
      type: "ฐานข้อมูล",
      description: "",
    },
    {
      source: "./assets/icons/NextJS-Dark.svg",
      alternate: "Next.js",
      title: "Next.js",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/icons/Nginx.svg",
      alternate: "Nginx",
      title: "Nginx",
      type: "เซิร์ฟเวอร์",
      description: "",
    },
    {
      source: "./assets/icons/NodeJS-Dark.svg",
      alternate: "Node.js",
      title: "Node.js",
      type: "รันไทม์",
      description: "",
    },
    {
      source: "./assets/icons/Notion-Dark.svg",
      alternate: "Notion",
      title: "Notion",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/icons/Npm-Dark.svg",
      alternate: "NPM",
      title: "NPM",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/NuxtJS-Dark.svg",
      alternate: "Nuxt.js",
      title: "Nuxt.js",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/icons/Photoshop.svg",
      alternate: "Photoshop",
      title: "Photoshop",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/icons/PostgreSQL-Dark.svg",
      alternate: "PostgreSQL",
      title: "PostgreSQL",
      type: "ฐานข้อมูล",
      description: "",
    },
    {
      source: "./assets/icons/Postman.svg",
      alternate: "Postman",
      title: "Postman",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Powershell-Dark.svg",
      alternate: "Powershell",
      title: "Powershell",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Python-Dark.svg",
      alternate: "Python",
      title: "Python",
      type: "ภาษา",
      description: "",
    },
    {
      source: "./assets/icons/React-Dark.svg",
      alternate: "React",
      title: "React",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/icons/Replit-Dark.svg",
      alternate: "Replit",
      title: "Replit",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Sketchup-Dark.svg",
      alternate: "Sketchup",
      title: "Sketchup",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/icons/SQLite.svg",
      alternate: "SQLite",
      title: "SQLite",
      type: "ฐานข้อมูล",
      description: "",
    },
    {
      source: "./assets/icons/StackOverflow-Dark.svg",
      alternate: "StackOverflow",
      title: "StackOverflow",
      type: "แอป",
      description: "",
    },
    {
      source: "./assets/icons/Supabase-Dark.svg",
      alternate: "Supabase",
      title: "Supabase",
      type: "คลาวด์",
      description: "",
    },
    {
      source: "./assets/icons/TailwindCSS-Dark.svg",
      alternate: "TailwindCSS",
      title: "TailwindCSS",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/icons/Vercel-Dark.svg",
      alternate: "Vercel",
      title: "Vercel",
      type: "โฮสต์",
      description: "",
    },
    {
      source: "./assets/icons/VisualStudio-Dark.svg",
      alternate: "Visual Studio",
      title: "Visual Studio",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/Vite-Dark.svg",
      alternate: "Vite",
      title: "Vite",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/VSCode-Dark.svg",
      alternate: "Visual Studio Code",
      title: "Visual Studio Code",
      type: "เครื่องมือ",
      description: "",
    },
    {
      source: "./assets/icons/VueJS-Dark.svg",
      alternate: "Vue.js",
      title: "Vue.js",
      type: "เฟรมเวิร์ค",
      description: "",
    },
    {
      source: "./assets/icons/Windows-Dark.svg",
      alternate: "Windows",
      title: "Windows",
      type: "ระบบปฎิบัติการ",
      description: "",
    },
    {
      source: "./assets/icons/Yarn-Dark.svg",
      alternate: "Yarn",
      title: "Yarn",
      type: "เครื่องมือ",
      description: "",
    },
  ],
};
